global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

# rule_files:
#  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'itu-minitwit-app'
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['itu-minitwit.duckdns.org:443']
        labels:
          group: 'production'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'itu-minitwit:5001'
        
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [
          '46.101.231.189:9100',
          '46.101.206.181:9100',
          '165.245.209.232:9100',
          '46.101.222.128:9100'
        ]
        labels:
          group: 'production'